#!/bin/bash
# Instructions to convert the markdown report to Word

echo "=============================================="
echo "Converting Assignment Report to Word Document"
echo "=============================================="
echo ""
echo "METHOD 1: Using pandoc (recommended)"
echo "If you have pandoc installed:"
echo "  pandoc ASSIGNMENT_REPORT.md -o ASSIGNMENT_REPORT.docx --reference-doc=template.docx"
echo ""
echo "METHOD 2: Using online converter"
echo "  1. Open https://www.markdowntoword.com/"
echo "  2. Upload ASSIGNMENT_REPORT.md"
echo "  3. Download the .docx file"
echo ""
echo "METHOD 3: Manual in Microsoft Word"
echo "  1. Open Microsoft Word"
echo "  2. File → Open → Select 'ASSIGNMENT_REPORT.md'"
echo "  3. Word will ask to convert - click 'OK'"
echo "  4. File → Save As → Select .docx format"
echo ""
echo "METHOD 4: Using Google Docs"
echo "  1. Open Google Docs"
echo "  2. File → Open → Upload 'ASSIGNMENT_REPORT.md'"
echo "  3. File → Download → Microsoft Word (.docx)"
echo ""
echo "The figures are already in outputs/ folder and referenced in the document."
echo "Make sure to insert them at the appropriate locations marked in the text."
echo ""
